Feat/modif user account
KD63799/deadlinedrive pull request #56
Opened 2024-07-15 13:50 UTC by jlaron230

This pull request introduces the following changes:

Addition of Express Validator: Integrated Express Validator to various endpoints to enhance data validation.
README Update: Added detailed documentation for the new data validation process and updated instructions for setting up and running the project.
Eye Icon Optimization: Improved the eye icons used for displaying password modification to enhance user experience and accessibility.
Changes Made
Express Validator Integration:

Installed Express Validator as a dependency.
Implemented validation middleware in the user-related routes to validate email, name, and other necessary fields.
Added validation error handling to ensure proper error messages are sent to the client.
README Update:

Added a new section on data validation, explaining how Express Validator is used in the project.
Updated setup instructions to include steps for installing Express Validator.
Included examples of API requests and responses showcasing the validation in action.
Eye Icon Optimization:

Updated the CSS and HTML for the eye icons to improve their appearance and responsiveness.
Ensured that the icons are accessible and provide a better user experience for password visibility toggling.

2024-07-15 13:55 UTC, CalliEtc approved these changes

2024-07-15 14:13 UTC, Childbutsmart requested changes
Here we go again...

2024-07-16 09:24 UTC, Childbutsmart approved these changes

2024-07-16 09:26 UTC, KD63799 approved these changes

2024-07-16 09:30 UTC, merged